### ISSUE TITLE
Logo is distorted on some screen resolutions

### ISSUE THREAD

**Issue by myrotvorets-team** [myrotvorets/report.myrotvorets.center#21]
CSS cascade issue:

```css
.Modal .inner > :only-child {
    max-width: 80vw;
    width: 60ch;
}
```

rules take priority over `width` and `max-width` set by `.Modal .Loader`
